### ISSUE TITLE
Error while reading the JSON from WS

### ISSUE THREAD

**Issue by stefanvdv** [NLNOG/bgpalerter#6]
Hi, 

When I try to run runner.py i get following output:

Subscribing to xxxx/23
Subscribing to xxxx/32
Subscribing to xxxx/24
Error while reading the JSON from WS
Error while reading the JSON from WS

Did you see this error before? 

Kind regards,

Stefan

**Comment by gstorme** [comment]
I also encountered this.
After enabling a more verbose output:

```
Error while reading the JSON from WS
Traceback (most recent call last):
  File "runner.py", line 56, in <module>
    alerter.monitor(to_be_monitored)
  File "/opt/bgpalerter/bgpalerter.py", line 56, in monitor
    self._ris.subscribe(self.monitored_prefixes)
  File "/opt/bgpalerter/ris_listener.py", line 194, in subscribe
    call(json_data)
  File "/opt/bgpalerter/bgpalerter.py", line 36, in <lambda>
    self._ris.on("error", lambda data: self._publish(self, "error", data))
TypeError: _publish() takes 3 positional arguments but 4 were given
```

Don't know how to fix it, but a workaround was to comment this line in bgpalerter.py:
`self._ris.on("error", lambda data: self._publish(self, "error", data)`

**Comment by nusenu** [comment]
same issue here
